// This file is autogenerated. Changes will be overwritten.
#include "6YEA5652QU/moc_LauncherWindow.cpp"
#include "6YEA5652QU/moc_MainWindow.cpp"
#include "26E4343VLD/moc_BitBuddyActionButton.cpp"
#include "26E4343VLD/moc_BitBuddyStatusWidget.cpp"
#include "Q6AU6LSD6J/moc_BitBuddy.cpp"
#include "OBZ36IEKUH/moc_BitBuddySpriteHandler.cpp"
#include "OBZ36IEKUH/moc_EventDispatcherService.cpp"
